# Generated by Django 4.1.7 on 2023-03-02 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floorno', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
                ('date', models.DateField(max_length=10)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phonenumber', models.CharField(max_length=30)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indoorapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=30)),
                ('shopnumber', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('Category', models.CharField(default='none', max_length=30)),
                ('logo', models.CharField(max_length=300)),
                ('phonenumber', models.CharField(max_length=30)),
                ('FLOOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indoorapp.floor')),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='indoorapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=30)),
                ('stock', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=30)),
                ('SHOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indoorapp.shop')),
            ],
        ),
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('validtill', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indoorapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotspotaddress', models.CharField(max_length=30)),
                ('SHOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indoorapp.shop')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indoorapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='emergencymessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergencymessage', models.CharField(max_length=30)),
                ('reply', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indoorapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indoorapp.user')),
            ],
        ),
    ]
