# Generated by Django 4.1.7 on 2023-03-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(default='none', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='time',
        ),
    ]
