# Generated by Django 4.1.7 on 2023-04-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoorapp', '0003_notification_shop_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopida', models.CharField(max_length=30)),
                ('shopidb', models.CharField(max_length=30)),
                ('direction', models.CharField(max_length=30)),
            ],
        ),
    ]
