# Generated by Django 4.1.7 on 2023-04-06 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indoorapp', '0004_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='shopida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopida', to='indoorapp.shop'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='shopidb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopidb', to='indoorapp.shop'),
        ),
    ]
