# Generated by Django 4.1.7 on 2023-04-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoorapp', '0005_alter_direction_shopida_alter_direction_shopidb'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='x_axis',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='shop',
            name='y_axis',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
