# Generated by Django 4.1.7 on 2023-04-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoorapp', '0006_shop_x_axis_shop_y_axis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='x_axis',
            field=models.IntegerField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='shop',
            name='y_axis',
            field=models.IntegerField(default='none', max_length=30),
        ),
    ]
