# Generated by Django 4.1.7 on 2023-04-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoorapp', '0008_remove_user_lastname_alter_emergencymessage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='type',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
